ALTER TABLE orders
ADD COLUMN IF NOT EXISTS customer_reference VARCHAR(100);

ALTER TABLE orders
ADD COLUMN IF NOT EXISTS customer_id VARCHAR(100);

ALTER TABLE orders
ADD COLUMN IF NOT EXISTS shipping_address_id VARCHAR(100);

ALTER TABLE orders
ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'created';

ALTER TABLE orders
ADD COLUMN IF NOT EXISTS currency VARCHAR(10) DEFAULT 'USD';

ALTER TABLE orders
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE orders
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;