from datetime import date
from decimal import Decimal
from enum import Enum
from pydantic import BaseModel, Field
from typing import List

class TimeGrain(str, Enum):
    daily = "daily"
    monthly = "monthly"

class SalesByPartnerItem(BaseModel):
    partner_name: str = Field(
        title="Partner Name",
        description="Name of the partner"
    )
    units_sold: int = Field(description="Total number of units sold by the partner")
    total_sales: Decimal = Field(description="Total revenue generated by the partner")

    model_config = {
        "json_schema_extra": {
            "example": {
                "partner_name": "RayTech Corp.",
                "units_sold": 31,
                "total_sales": 16247.94
            }
        }
    }


class SalesByPartnerResponse(BaseModel):
    analytics_type: str = Field(description="Type of analytics result returned")
    results: List[SalesByPartnerItem] = Field(description="List of partner-level sales metrics")

    model_config = {
        "json_schema_extra": {
            "example": {
                "analytics_type": "sales_by_partner",
                "results": [
                    {
                        "partner_name": "RayTech Corp.",
                        "units_sold": 31,
                        "total_sales": 16247.94
                    },
                    {
                        "partner_name": "Microbrews Brothers",
                        "units_sold": 49,
                        "total_sales": 1599.98
                    }
                ]
            }
        }
    }


class SalesOverTimeItem(BaseModel):
    sales_period: date = Field(description="Date or month representing the aggregation period")
    units_sold: int = Field(description="Total units sold during the period")
    total_sales: Decimal = Field(description="Total revenue during the period")

    model_config = {
        "json_schema_extra": {
            "example": {
                "sales_period": "2026-04-01",
                "units_sold": 80,
                "total_sales": 17847.92
            }
        }
    }


class SalesOverTimeResponse(BaseModel):
    analytics_type: str = Field(description="Type of analytics result returned")
    grain: TimeGrain = Field(
        description="Aggregation level applied to the time-series data. Supported values: 'daily', 'monthly'.")
    results: List[SalesOverTimeItem] = Field(description="List of aggregated sales metrics by time period")

    model_config = {
        "json_schema_extra": {
            "example": {
                "analytics_type": "sales_over_time",
                "grain": "monthly",
                "results": [
                    {
                        "sales_period": "2026-04-01",
                        "units_sold": 80,
                        "total_sales": 17847.92
                    }
                ]
            }
        }
    }

class RevenueShareItem(BaseModel):
    partner_name: str = Field(
        description="Name of the partner"
    )
    total_revenue: Decimal = Field(
        description="Total revenue generated by the partner"
    )
    revenue_pct: float = Field(
        description="Percentage of total revenue contributed by the partner"
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "partner_name": "RayTech Corp.",
                "total_revenue": 14759.79,
                "revenue_pct": 96.40
            }
        }
    }


class RevenueShareResponse(BaseModel):
    analytics_type: str = Field(
        description="Type of analytics result returned"
    )
    results: List[RevenueShareItem] = Field(
        description="List of partners with their revenue contribution percentages"
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "analytics_type": "revenue_share",
                "results": [
                    {
                        "partner_name": "RayTech Corp.",
                        "total_revenue": 14759.79,
                        "revenue_pct": 96.40
                    },
                    {
                        "partner_name": "Microbrews Brothers",
                        "total_revenue": 552.01,
                        "revenue_pct": 3.60
                    }
                ]
            }
        }
    }